// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn4_cLh3mLQrnH-FE0DoI6ZY3cV883OVE',
    appId: '1:172639566626:web:57602d9d18a9e7042c437b',
    messagingSenderId: '172639566626',
    projectId: 'gard-project-mobile-app',
    authDomain: 'gard-project-mobile-app.firebaseapp.com',
    storageBucket: 'gard-project-mobile-app.firebasestorage.app',
    measurementId: 'G-LNHVLNMLJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbN_bExyNK6deuW46kyFXXqqxQkoOCjew',
    appId: '1:172639566626:android:5adafea545b88bc72c437b',
    messagingSenderId: '172639566626',
    projectId: 'gard-project-mobile-app',
    storageBucket: 'gard-project-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2rJYMe8Vd2kXOG_wwcjBTeiqonnSqAgI',
    appId: '1:172639566626:ios:8f67a7c1d09634ab2c437b',
    messagingSenderId: '172639566626',
    projectId: 'gard-project-mobile-app',
    storageBucket: 'gard-project-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.gradIiMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2rJYMe8Vd2kXOG_wwcjBTeiqonnSqAgI',
    appId: '1:172639566626:ios:8f67a7c1d09634ab2c437b',
    messagingSenderId: '172639566626',
    projectId: 'gard-project-mobile-app',
    storageBucket: 'gard-project-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.gradIiMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn4_cLh3mLQrnH-FE0DoI6ZY3cV883OVE',
    appId: '1:172639566626:web:946d55e06df7b8a32c437b',
    messagingSenderId: '172639566626',
    projectId: 'gard-project-mobile-app',
    authDomain: 'gard-project-mobile-app.firebaseapp.com',
    storageBucket: 'gard-project-mobile-app.firebasestorage.app',
    measurementId: 'G-F62LNRPNQ8',
  );
}
